### ISSUE TITLE
Problem with DatabaseTransactions

### ISSUE THREAD

**Issue by V-Srv** [fntneves/laravel-transactional-events#13]
Hello,

In my tests I am using DatabaseTransactions trait. Because of that I still have a problem that you resolved with Neves\RefreshDatabase trait. All events are fired after the outer transaction which happens after the end of the test.

Could you create a fix for DatabaseTransactions trait as well?

**Comment by fntneves** [comment]
Hello,

Thank you for your issue.

Any reason to use `DatabaseTransactions` instead of `RefreshDatabase`? They do the same thing, but the latter adapts the behavior according to the kind of database you are using (in-memory uses migrations, others use transactions).

**Comment by V-Srv** [comment]
Yeah, I guess it was a force of habit since the earlier versions of Laravel.

I'll begin to use `RefreshDatabase` in a short period of time since it is a recommended way now. 

This issue could be closed.

**Comment by LastDragon-ru** [comment]
> Any reason to use DatabaseTransactions instead of RefreshDatabase?

The `RefreshDatabase` (= `migrate:fresh`) is extremely slow when you have a lot of migrations.

**Comment by fntneves** [comment]
Hello @LastDragon-ru,

According to Laravel documentation, the RefreshDatabase is smart enough to use migrations when dealing to in-memory database (sqlite) and transactions otherwise. So, it is recommended to use RefreshDatabase trait.

**Comment by LastDragon-ru** [comment]
@fntneves , sqlite is very limited and usually (in big real app) is not possible to use it + migrations аre also very limited (is not possible to change emun for example) and there are many other cases when you should you raw sql which may be incompatible with other db. 

Also, when you have a few tens or hundreds of migrations is really VERY slowly to run it all before each test. (this is the main reason why I use `DatabaseTransactions`).

**Comment by fntneves** [comment]
@LastDragon-ru Thank you for your explanation. I'm just trying to understand your concern, so I can consider the possibility to add a trait that meets this issue.

If you prepare your database and reuse it to while running the whole test suite multiple times (for instance, calling `phpunit` multiple times), I agree that using `DatabaseTransactions` is better than using the `RefreshDatabase` trait.
Is this your use case?

**Comment by LastDragon-ru** [comment]
@fntneves , yes, moreover I always use the same pre-created test db. It is possible to recreate it before each phpunit run/testsuite but it is not necessary in my case.

**Comment by mpyw** [comment]
[Add DatabaseTransactions trait for transactional events by mfn · Pull Request #28 · fntneves/laravel-transactional-events](https://github.com/fntneves/laravel-transactional-events/pull/28)
