### ISSUE TITLE
Using DatabaseTransactions

### ISSUE THREAD

**Issue by ggelashvili** [fntneves/laravel-transactional-events#25]
Hello,

I use DatabaseTransactions trait which does not work with TransactionalEvent. Seems like it's solved if I use Neves\RefreshDatabase trait but I am trying to avoid using RefreshDatabase since I have a lot of migration files & rerunning migrations for each test takes a lot of time. Is there a fix for DatabaseTransactions?

**Comment by fntneves** [comment]
Hello,

The `RefreshDatabase` trait does not rollback migrations if the database is not in memory, it only does for SQLite. For MySQL or PostgreSQL, it uses transactions under the hood to rollback changes made in a test before running to the next one.

Use the `RefreshDatabase` trait, you will see no difference in execution time.

**Comment by mpyw** [comment]
[Add DatabaseTransactions trait for transactional events by mfn · Pull Request #28 · fntneves/laravel-transactional-events](https://github.com/fntneves/laravel-transactional-events/pull/28)
