### ISSUE TITLE
Support for Laravel 6

### ISSUE THREAD

**Issue by erikgaal** [fntneves/laravel-transactional-events#30]
Opening this issue to keep track of the Laravel 6 support for this package.

**Comment by fntneves** [comment]
Hi @erikgaal 

I'm working on it. :+1:

Will be available during this week.

**Comment by erikgaal** [comment]
Awesome! No pressure and good luck! <3

**Comment by fntneves** [comment]
It is done, now!

If you have any further issues, let me know!

Thank you for using this package.
