### ISSUE TITLE
 drupol/phptree is abandoned

### ISSUE THREAD

**Issue by goldendousa** [fntneves/laravel-transactional-events#37]
I noticed that you are using  drupol/phptree which is no longer maintained in packagist.

_This package is abandoned and no longer maintained. The author suggests using the loophp/phptree package instead._

**Comment by goldendousa** [comment]
changing **drupal\phptree\Node\ValueNode** to  l**oophp\phptree\Node\ValueNode**
and 
**drupal\phptree\Node\ValueNodeInterface** to **loophp\phptree\Node\ValueNodeInterface**

is enough i guess..

**Comment by mfn** [comment]
PR was already here, see https://github.com/fntneves/laravel-transactional-events/pull/36
