### ISSUE TITLE
Please remove the global function introduced with 1.8.8

### ISSUE THREAD

**Issue by mfn** [fntneves/laravel-transactional-events#39]
See https://github.com/fntneves/laravel-transactional-events/releases/tag/1.8.8

This is a very sad move. The Laravel community suffers and tries really hard to get rid of all the global helper functions. There are countless occurrences of this laravel/framework issues and PRs introducing global helper function are closed (almost?) all cases. That's also the reason why some of the helpers were moved into a dedicated package ( https://github.com/laravel/helpers )

It wouldn't be such a problem if it were _optional_, but it isn't: it's forced upon users on installation, the `helpers.php` file through composer is forcefully loaded.

It uses `function_exists` but you will find it's actually _not easy_ to truly override this.

I would like to ask to reconsider this addition, thank you!

**Comment by fntneves** [comment]
I get your point.

I was convicted it would be good for most cases, but I understand :+1:

Will get rid of this and encourage the use of TransactionalClosureEvent directly.

**Comment by fntneves** [comment]
Fixed in https://github.com/fntneves/laravel-transactional-events/tree/1.8.9

**Comment by mfn** [comment]
A big big thank you for listening 🤗
