### ISSUE TITLE
What is the best way to apply to all observers?

### ISSUE THREAD

**Issue by ibrunotome** [fntneves/laravel-transactional-events#40]
Hello, I use observers for every Model, like UserObserver, OrderObserver, etc...

If I modify the `excluded` setting to `'excluded' => []`, all the eloquent events in the Observers will be transactional?

**Comment by fntneves** [comment]
Hi @ibrunotome,

Yes, in [this](https://github.com/fntneves/laravel-transactional-events/blob/master/tests/TransactionalEloquentTest.php#L42) test case, you  can see that removing Eloquent events from excluded option, all `eloquent.*` events will be considered in the transaction-aware layer.

**Comment by ibrunotome** [comment]
Thanks for this `halt = true` info. Normally I dispatch a notification from the `created()` method, so will be better dispatch an event (this event will be in App\Events and be transactional) from the created method, an this event dispatch the notification, right? Thanks!
